version: "3"

services:
  app1:
    image: crud
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
  postgres:
    container_name: parking
    image: postgres
    environment:
      POSTGRES_DB: "egormelnikovdb"
      POSTGRES_USER: "egormelnikov"
      POSTGRES_PASSWORD: "54236305"
    ports:
      - "5444:5432"
  mongo:
    container_name: parking_mongo
    image: mongo
    environment:
      -MONGO_INITDB_DATABASE: "egormelnikovdb"
    ports:
      - "27072:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"