// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/EgMeln/CRUDentity/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Authentication is an autogenerated mock type for the Authentication type
type Authentication struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: e, user
func (_m *Authentication) SignIn(e context.Context, user *model.User) (string, string, error) {
	ret := _m.Called(e, user)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) string); ok {
		r0 = rf(e, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, *model.User) string); ok {
		r1 = rf(e, user)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *model.User) error); ok {
		r2 = rf(e, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
