// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/EgMeln/CRUDentity/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ParkingLotCacheRedis is an autogenerated mock type for the ParkingLotCacheRedis type
type ParkingLotCacheRedis struct {
	mock.Mock
}

// Add provides a mock function with given fields: e, lot
func (_m *ParkingLotCacheRedis) Add(e context.Context, lot *model.ParkingLot) error {
	ret := _m.Called(e, lot)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ParkingLot) error); ok {
		r0 = rf(e, lot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: e, num
func (_m *ParkingLotCacheRedis) Delete(e context.Context, num int) error {
	ret := _m.Called(e, num)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(e, num)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByNum provides a mock function with given fields: e, num
func (_m *ParkingLotCacheRedis) GetByNum(e context.Context, num int) (*model.ParkingLot, error) {
	ret := _m.Called(e, num)

	var r0 *model.ParkingLot
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.ParkingLot); ok {
		r0 = rf(e, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ParkingLot)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(e, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
