// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/EgMeln/CRUDentity/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Tokens is an autogenerated mock type for the Tokens type
type Tokens struct {
	mock.Mock
}

// Add provides a mock function with given fields: e, token
func (_m *Tokens) Add(e context.Context, token *model.Token) error {
	ret := _m.Called(e, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Token) error); ok {
		r0 = rf(e, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: e, username
func (_m *Tokens) Delete(e context.Context, username string) error {
	ret := _m.Called(e, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(e, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: e, username
func (_m *Tokens) Get(e context.Context, username string) (string, error) {
	ret := _m.Called(e, username)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(e, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(e, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
